version: '2'

services:
  node-app:
    image: node:6
    ports:
      - "3000:3000"
    environment:
      - DEBUG=myapp:*
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    depends_on:
      - mysql
    links:
      - mysql:db
    command: /bin/bash -c "npm install && npm start"
  mysql:
    image: mysql:5.6
    ports:
      - "3506:3306"
    environment:
      - MYSQL_DATABASE=myapp_develop
      - MYSQL_ROOT_PASSWORD=supersecret
    volumes:
      - ./docker/develop/entrypoint:/docker-entrypoint-initdb.d
