version: '2'

services:
  node:
    image: node:6
    ports:
      - "3000:3000"
    environment:
      - DEBUG=myapp:*
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    depends_on:
      - mongo
    links:
      - mongo:db
    command: /bin/bash -c "npm install && npm start"
  mongo:
    image: mongo:3.0
    ports:
      - "27017:27017"
    volumes:
      - ./docker/develop/data:/data/db
